import { type DynamicStructuredTool } from "@langchain/core/tools";
import {
  appendFileTool,
  copyDirectoryTool,
  copyFileTool,
  createDirectoryTool,
  deleteFileTool,
  extractZipTool,
  fileExistsTool,
  insertIntoFileTool,
  listDirectoryTool,
  makeZipTool,
  moveDirectoryTool,
  moveFileTool,
  openPathTool,
  openUrlTool,
  pathStatTool,
  readFileTool,
  readCsvTool,
  readJsonTool,
  replaceRegexInFileTool,
  replaceInFileTool,
  revealInFolderTool,
  searchFileContentTool,
  searchFilesTool,
  writeJsonTool,
  writeFileTool,
} from "./fileTools";
import {
  calculatorTool,
  clipboardCopyTool,
  currentTimeTool,
  listRunningAppsTool,
  listSpecialFolderTool,
  osInfoTool,
  systemTools,
  unitConvertTool,
} from "./systemTools";
import {
  currentWeatherTool,
  currencyConvertTool,
  fetchUrlTool,
  webSearchTool,
  webTools,
} from "./webTools";
import { generatePdfTool, generatePptxTool, reportTools } from "./reportTools";

export {
  readFileTool,
  writeFileTool,
  appendFileTool,
  createDirectoryTool,
  copyFileTool,
  copyDirectoryTool,
  listDirectoryTool,
  readJsonTool,
  readCsvTool,
  fileExistsTool,
  pathStatTool,
  insertIntoFileTool,
  writeJsonTool,
  replaceInFileTool,
  replaceRegexInFileTool,
  makeZipTool,
  openUrlTool,
  extractZipTool,
  revealInFolderTool,
  openPathTool,
  moveFileTool,
  moveDirectoryTool,
  deleteFileTool,
  searchFilesTool,
  searchFileContentTool,
  currentTimeTool,
  osInfoTool,
  calculatorTool,
  unitConvertTool,
  clipboardCopyTool,
  listRunningAppsTool,
  listSpecialFolderTool,
  webSearchTool,
  currentWeatherTool,
  fetchUrlTool,
  currencyConvertTool,
  generatePdfTool,
  generatePptxTool,
};

export const allTools: DynamicStructuredTool[] = [
  readFileTool,
  writeFileTool,
  appendFileTool,
  createDirectoryTool,
  copyFileTool,
  copyDirectoryTool,
  listDirectoryTool,
  readJsonTool,
  readCsvTool,
  fileExistsTool,
  pathStatTool,
  insertIntoFileTool,
  writeJsonTool,
  replaceInFileTool,
  replaceRegexInFileTool,
  makeZipTool,
  openUrlTool,
  extractZipTool,
  revealInFolderTool,
  openPathTool,
  moveFileTool,
  moveDirectoryTool,
  deleteFileTool,
  searchFilesTool,
  searchFileContentTool,
  ...systemTools,
  ...webTools,
  ...reportTools,
];
